services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sites:/var/www/html
    ports:
      - "85:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: dictionary

volumes:
  mysql: