services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sites:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql:
  jenkins_home:

networks:
  jenkins-network: